### ISSUE TITLE
Database is not generated on startup

### ISSUE THREAD

**Issue by rezalas** [rezalas/riftshadow#4]
When the program starts up it should check to see if the database exists, and if not it should (given the proper working credentials) create the database it needs in a default "empty" state.

**Comment by sean-gilliam** [comment]
I'm not sure if this is possible with `mysqlclient` since it requires an active database in order to connect. We'd have to drop down to shell commands which seems kind iffy and has security issues. 

Best we use what @marado coded. If the db isn't present, then have the server maintainer go through the steps on setting up the db with our provided steps and then start the server back up.

Just my 2c.

**Comment by rezalas** [comment]
This is a good point. I think we're good with what we have. When we add logging we can improve the detection with a meaningful message as well, which will make this even more moot.
